name: Close TW Pull Request

on:
  pull_request_target:
    types: [opened]
    paths: previous-seasons/2021-participants/interested-technical-writers.md

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        # Optional. Post a issue comment just before closing a pull request.
        comment: "The 2021 program, so we're closing this PR. If you are interested in participating in the 2022 program, please add your information to the [2022 interested technical writers](https://github.com/google/season-of-docs/blob/main/2022-participants/interested-technical-writers.md) list. Please feel free to subscribe to our [announcements list](https://groups.google.com/g/season-of-docs-announce) for information about upcoming Season of Docs programs."
